# Generated by Django 2.2.11 on 2020-03-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_vendor', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_category', models.CharField(max_length=255)),
                ('engine_type', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=255)),
                ('km', models.IntegerField()),
                ('first_registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='STKInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_id', models.IntegerField()),
                ('inspection_type', models.CharField(max_length=255)),
                ('inspection_time', models.DateTimeField()),
                ('zav_a', models.IntegerField()),
                ('zav_b', models.IntegerField()),
                ('zav_c', models.IntegerField()),
                ('inspection_result', models.CharField(max_length=255)),
                ('emission_result', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stk.Vehicle')),
            ],
        ),
    ]
