# Generated by Django 2.2.11 on 2020-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
