# Generated by Django 2.2.11 on 2020-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0003_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stk_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
