# Generated by Django 2.2.11 on 2020-06-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0008_auto_20200614_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precalculatedstatistic',
            old_name='inspected_vehicles_number',
            new_name='number_of_inspections',
        ),
    ]
