# Generated by Django 2.2.11 on 2020-06-15 16:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0011_vehicle_vehicle_vendor_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=django.contrib.postgres.indexes.HashIndex(fields=['vehicle_vendor_model'], name='stk_vehicle_vehicle_19df1f_hash'),
        ),
    ]
