# Generated by Django 2.2.11 on 2020-06-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0012_auto_20200615_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='map_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='map_y',
            field=models.IntegerField(default=0),
        ),
    ]
