# Generated by Django 2.2.11 on 2020-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0013_auto_20200615_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='number_of_inspections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='pass_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
